name: build-and-test

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies
      - run: yarn install

      # Build all packages
      - run: yarn run build

      # Bundle meta package
      - run: yarn run bundle

      # Run tests for all packages
      - run: yarn run test